# Generated by Django 6.0.3 on 2026-04-25 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='burnoutrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='burnoutrecord',
            name='sleep_hours',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
