# Generated by Django 6.0.3 on 2026-04-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_burnoutrecord_created_at_burnoutrecord_sleep_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='burnoutrecord',
            name='risk_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='burnoutrecord',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
    ]
